#include <algorithm>
#include <stdexcept>
#include <string>
#include <vector>

#include <barq/impl/simulated_failure.hpp>
#include <barq/string_data.hpp>
#include <barq/sync/client.hpp>
#include <barq/sync/network/default_socket.hpp>
#include <barq/sync/network/http.hpp>
#include <barq/sync/network/network.hpp>
#include <barq/sync/noinst/client_history_impl.hpp>
#include <barq/sync/noinst/migration_store.hpp>
#include <barq/sync/noinst/protocol_codec.hpp>
#include <barq/sync/noinst/server/server.hpp>
#include <barq/sync/noinst/server/server_dir.hpp>
#include <barq/transaction.hpp>
#include <barq/version.hpp>

#include "test.hpp"

namespace barq::fixtures {

using namespace barq::sync;
using namespace barq::test_util;

// This public key must match the private key used to sign the token
// below (test.pem).
const char g_test_server_key_path[] = "test_pubkey.pem";

inline std::string test_server_key_path()
{
    return get_test_resource_path() + g_test_server_key_path;
}

// The Base64-encoded user token is generated by the following command:
//     cat test_token.json | base64
// The Base64-encoded signature is generated by the following command:
//     cat test_token.json | openssl dgst -sha256 -binary -sign test.pem | base64
// The two are concatenated with a ':'.
// This token does not contain a "path" field, and therefore grants access to
// all Barqs.
const char g_signed_test_user_token[] =
    "ewogICAgImlkZW50aXR5IjogInRlc3QiLAogICAgImFjY2VzcyI6IFsiZG93bmxvYWQiLCAidXBsb2FkIl0sCiAgICAidGlt"
    "ZXN0YW1wIjogMTQ1NTUzMDYxNCwKICAgICJleHBpcmVzIjogbnVsbCwKICAgICJhcHBfaWQiOiAiaW8uYmFycS5UZXN0Igp9"
    "Cg==:gf2EBD/k2ZNQYFO07x2dRICigg/sWC//YODgq47tArdEW3wcalUImJQt6r7gnowKfehb63XYn6bM3aNUdQPGy4wqVTa"
    "1Xa1g0Q897+XNK0DIe3Zb4bB/tfcdUbzmaHQDJ6n2Bns19KEdWSuOxz9JjYjTraKMbzXvfDV5xjiufZ57wYJs5Ba743ijnPY"
    "En5RE2vY/B2G8mVMN+6aWUoBetnTOxKNylK5qNKdb1tFEZ7Be5199O9O10FKaFO7p8W0nQtGwkrjbTo8Y4IziGgs+2Lha60f"
    "/n1NSoNa3i8lL5Hi+Z7tHeufFkSpnDDrzcq+TDCGaj3GI5LhK2nbU03SAcQ==";

const char g_unsigned_test_user_token[] =
    "ewogICAgImlkZW50aXR5IjogInRlc3QiLAogICAgImFjY2VzcyI6IFsiZG93bmxvYWQiLCAidXBsb2FkIl0sCiAgICAidGlt"
    "ZXN0YW1wIjogMTQ1NTUzMDYxNCwKICAgICJleHBpcmVzIjogbnVsbCwKICAgICJhcHBfaWQiOiAiaW8uYmFycS5UZXN0Igp9"
    "Cg==";


// Token for user_0.
//{
//    "identity": "user_0",
//    "admin": false,
//    "timestamp": 1455530614,
//    "expires": null,
//    "app_id": "io.barq.Test"
//}
const char g_user_0_token[] =
    "ewogICAgImlkZW50aXR5IjogInVzZXJfMCIsCiAgICAiYWRtaW4iOiBmYWxzZSwKICAgICJ0aW1lc3RhbXAiOiAxNDU1NTMw"
    "NjE0LAogICAgImV4cGlyZXMiOiBudWxsLAogICAgImFwcF9pZCI6ICJpby5iYXJxLlRlc3QiCn0K:weZE3Jtyeq9VAB73S6m"
    "gi2k3bM+DITtu1Sb77kcxBZPSxGyxMhO0SkVNMqNL634qXbzayoaCwh6ikAmWtr2htef7QD9I6ayZVkafGoDrAWSkhJqHvED"
    "LH95OEn+2y0j3e5uDnHCz7E5pNH6I2o5vk4LQ9119589CB5ujMMthWkggxXPG8bXVWfmHfH75aBXsPSkPm8Zk0t2Pi4fsId8"
    "GJReg/ll2KEN3tW3ARjbzjdLuV/0dgHo5OOFAPGXEClVqYxbXiVa4T5V795K960BlEmAPzSqT5PHVil1JAt9HErefU2bYg5r"
    "kMHtLfvkye05dVbAFDM/eYz1mMm5RmTv8dA==";


// Token for user_1.
// {
//    "identity": "user_1",
//    "admin": false,
//    "timestamp": 1455530614,
//    "expires": null,
//    "app_id": "io.barq.Test"
//}
const char g_user_1_token[] =
    "ewogICAgImlkZW50aXR5IjogInVzZXJfMSIsCiAgICAiYWRtaW4iOiBmYWxzZSwKICAgICJ0aW1lc3RhbXAiOiAxNDU1NTMw"
    "NjE0LAogICAgImV4cGlyZXMiOiBudWxsLAogICAgImFwcF9pZCI6ICJpby5iYXJxLlRlc3QiCn0K:Eu0JZcbFkKynuutJ+qT"
    "GvnOxcY+IR3ahVEkI4xjViON1IvWf1p4J27YsnNTheNoz+ldeCC37vr2aMG++d56XuissU/pHV4cvTrts9jOr2qvaMXtyt9/"
    "++rsMaDndwrvAcr+Bcr57lR26q7yluk6tQGzybG9C9k0fPGS29pvz2Jxc1oqYtyV6kEsJjnji0dGGuF+VTA90qJL7VKb14tR"
    "mkvuIM2P3xh1uKzH9w3fFogrAs91FHEuK3zWxvpytBbeJ3mzduOFcLjmjjpFCpgbvrGlc5NBX1boIpxxhqEQkXsxez0noLN+"
    "FLiFb5Zu13Z0KbBcKALUwZgQ6j4FOvMftYQ==";


// Token for user_2.
// {
//    "identity": "user_2",
//    "admin": false,
//    "timestamp": 1455530614,
//    "expires": null,
//    "app_id": "io.barq.Test"
// }
const char g_user_2_token[] =
    "ewogICAgImlkZW50aXR5IjogInVzZXJfMiIsCiAgICAiYWRtaW4iOiBmYWxzZSwKICAgICJ0aW1lc3RhbXAiOiAxNDU1NTMw"
    "NjE0LAogICAgImV4cGlyZXMiOiBudWxsLAogICAgImFwcF9pZCI6ICJpby5iYXJxLlRlc3QiCn0K:ZP3cNkWKFqDhniz2Ja/"
    "pA1e5ey53W9BqVbpV8BA7q2ba8iytrUYVzo46wCYLehKUu+vtP91+hwEYJjcY1XeLtxk1VPIYHnpOJJEYChWl1yI7nSCwECA"
    "Z7QRVk5FkPOQ/AYdYnY40FLM6N3lSTwvoNUCJr6mvL3LkyUUtT54jk8OwLrGYJLkoDfIa0X0rWsRFtLFA8rmxs22XRGqxT14"
    "duvEU2Pba4okYV+3KAvZcD4ivukqcryRikf/j3FukFxqz+H5/XjS3X50223BJ3FB/HiNVgsTyL105nlPpZLjL0l9s2sssA2S"
    "dwAjkAZABpa7UMpaI+7kWXvSZqxwfZH+huQ==";


// {
//     "identity": "user_0",
//     "admin": false,
//     "timestamp": 1455530614,
//     "expires": null,
//     "app_id": "io.barq.Test",
//     "path": "/test",
//     "access": ["download", "upload", "manage"]
// }
const char g_user_0_path_test_token[] =
    "ewogICAgImlkZW50aXR5IjogInVzZXJfMCIsCiAgICAiYWRtaW4iOiBmYWxzZSwKICAgICJ0aW1lc3RhbXAiOiAxNDU1NTMw"
    "NjE0LAogICAgImV4cGlyZXMiOiBudWxsLAogICAgImFwcF9pZCI6ICJpby5iYXJxLlRlc3QiLAogICAgInBhdGgiOiAiL3Rl"
    "c3QiLAogICAgImFjY2VzcyI6IFsiZG93bmxvYWQiLCAidXBsb2FkIiwgIm1hbmFnZSJdCn0K:oPjz3d3zQyDFyzbhbcsLpMe"
    "PVEFo4f8vH1D/IUZPf0CSIRABQIFggfBnqi4YnDw+SkLmN//5JYrAcl9Em+hTqy+61KKgJhXiYaZSN2jmtouvO2481j8o7FW"
    "rHth8rdI0nd4UdeuXV68GbSMPEbeIOLoFDAZ8oGGPgbM9oYo+jsK44T2hlRHuzpgb0+ZNBgSuIJwViqf5fp2kjwLLoWa5Mcp"
    "j6nOOgkBG9JxGa2bruggI0HNpAK5/XnS4RspZWerADji/ZOSCiPtnObLgGe+LWyI9bLI11n2JcoWYT988leAJgGBTSXTM2mY"
    "ycmTVWNWmneoCyzN9VXs2wp4IqMA4ng==";


// {
//     "identity": "user_1",
//     "admin": false,
//     "timestamp": 1455530614,
//     "expires": null,
//     "app_id": "io.barq.Test",
//     "path": "/test",
//     "access": ["download", "upload", "manage"]
// }
const char g_user_1_path_test_token[] =
    "ewogICAgImlkZW50aXR5IjogInVzZXJfMSIsCiAgICAiYWRtaW4iOiBmYWxzZSwKICAgICJ0aW1lc3RhbXAiOiAxNDU1NTMw"
    "NjE0LAogICAgImV4cGlyZXMiOiBudWxsLAogICAgImFwcF9pZCI6ICJpby5iYXJxLlRlc3QiLAogICAgInBhdGgiOiAiL3Rl"
    "c3QiLAogICAgImFjY2VzcyI6IFsiZG93bmxvYWQiLCAidXBsb2FkIiwgIm1hbmFnZSJdCn0K:XgmIDQCexRHQ5US9Zv3LtKM"
    "zlWezxYwnmZGtZQT6XW3lzmuF1wsnQZd1ENYvoCw6C5F6JArUX2xM0lItME+OIs5y7QnZ9YWH4biZPxQaC6OYwNewxaIbBNW"
    "pqJbR9VzHuLvHxRvSx4wKY72Ho+1xGaL1MiQclN7+lUTowNKLnE9S53q89wwBY8e2h28vP+Zvs7dX3nQmKmnpZB5OcdTkCpY"
    "rJIeM3p1IrUYdfa6NT43cnKGD7zgjeInJHRdwrpf7DTFi7SUJFDwYB20zXjfFKS2plVSSJNjYaQqlEYiuNCCGLheSbg3XDp+"
    "2QyERm0ZpBZ3fcYVXPzLt0U1E1Ddcfg==";

const char g_admin_path_test_token[] =
    "ewogICAgImlkZW50aXR5IjogImFkbWluIiwKICAgICJ0aW1lc3RhbXAiOiAxNDU1NTMwNjE0LAogICAgImV4cGlyZXMiOiBu"
    "dWxsLAogICAgImFwcF9pZCI6ICJpby5iYXJxLlRlc3QiLAogICAgInBhdGgiOiAiL3Rlc3QiLAogICAgImFjY2VzcyI6IFsi"
    "ZG93bmxvYWQiLCAidXBsb2FkIiwgIm1hbmFnZSJdCn0K:Zw74T5B/Fe1rkAOmZs5FneT0QcBQeCyYdYyNDIvG9PnnwG5mJtl"
    "gRIA8m20UpBK+pxZC084W48qeUlA9FPlo9PKxhkyfjuJbj+Jk44IJLTXKB86IoTlSIMGbN1jMbbmWZcHypERY4dZFb0fQZFS"
    "20rLlGs9s2+jBXGeMl6oiFdgRSG8CXhHIjsmwoMGcZbzlj15afpQK2SZ5gVCLePDtKF7K/p/5UHM9AQ4v5KgdEs4mqMXDZji"
    "EkVRKyxy0AVPaoGzBbDcVZ3sdPu/D6+nfgtpDkd1ciTFa+3oHoEXYhe8XdAYfEpDLPCAet7pWVNOO8v3VP8nc2AI877tcIxY"
    "cGw==";


// Generated from test_token_readonly.json
// This token does not contain a "path" field, and therefore grants access to
// all Barqs.
const char g_signed_test_user_token_readonly[] =
    "ewogICAgImlkZW50aXR5IjogInRlc3QiLAogICAgImFjY2VzcyI6IFsiZG93bmxvYWQiXSwKICAgICJ0aW1lc3RhbXAiOiAx"
    "NDU1NTMwNjE0LAogICAgImV4cGlyZXMiOiBudWxsLAogICAgImFwcF9pZCI6ICJpby5iYXJxLlRlc3QiCn0K:Rfd7ZML0Vh3"
    "XwuBcW5YiTx++asMNCgJaEkuYCfCnc2f4mdnFdS2lBk64K9zKwt7oCoX+DbEWA07vyWuzP9mi2ea1SYFPPdepd4TprR/Ewfs"
    "CHBbMplVjKTKWGE02wl4u93Ij5rOPk5/VGpZ/sbG5npwjeB3pZ03qbJHY4nMwV12H2GY8wNcK9mKUOLZ865fHIJWzeQlWSm7"
    "tTdSizVigyWdU9xseJVU74qGfuHnpxOHc+JvjAUQhtYW2Zl8TAcPMYp0rCF9iYflO6G79hF4oz4FoeRRWjUvbNft24MNIWYw"
    "OSb0luuUThXtCs5FNrFKEyMF0c9xZ/nAJIgA8tB05zg==";

// Generated from test_token_for_path.json
// This token only grants access to the server path "/valid".
const char g_signed_test_user_token_for_path[] =
    "ewogICAgImlkZW50aXR5IjogInRlc3QiLAogICAgImFjY2VzcyI6IFsiZG93bmxvYWQiLCAidXBsb2FkIl0sCiAgICAidGlt"
    "ZXN0YW1wIjogMTQ1NTUzMDYxNCwKICAgICJleHBpcmVzIjogbnVsbCwKICAgICJhcHBfaWQiOiAiaW8uYmFycS5UZXN0IiwK"
    "ICAgICJwYXRoIjogIi92YWxpZCIKfQo=:JDVzaq13fPZzlbhuqcYRtPeFc7ALzyqv2qvDmulI3bN1M/xqWq7Wx5m/XuHDdIp"
    "FRYpToak5H4gDmogLsJs+OtNrGq+gub7YsZZ2iz0wwX8+Cpnr3UdIPwLgtpZ5VO2di2x3lP6i+iJtrHTz35sK6jVgwwaoaZq"
    "hDm5wH1bJJP2oxFfNMM4D/7OXo+nAjzJBb3waFiU8m1yeG3Bhiu4f/Bxqb2CUTyg1KC1WNUowTOHM7QbPueOjwh68JutS6hs"
    "MykfkVp4NgqUHb8j66rKn8qjTIBWOQUF3yY1/egSxmf9Au4awCAuriBxU1aA+1ubbjkKOAJO3a0mrS3mE9j5KlQ==";

// Generated from test_token_expiration_unspecified.json
const char g_signed_test_user_token_expiration_unspecified[] =
    "ewogICAgImlkZW50aXR5IjogInRlc3QiLAogICAgImFjY2VzcyI6IFsiZG93bmxvYWQiLCAidXBsb2FkIl0sCiAgICAidGlt"
    "ZXN0YW1wIjogMTQ1NTUzMDYxNCwKICAgICJhcHBfaWQiOiAiaW8uYmFycS5UZXN0Igp9Cg==:K/GXcY0U4rcJG8tGWeFxC0l"
    "u6u56NTvdQBDMvCUhFSXCzKK33mkAoXtX0eP8Gx+Ww8qnCCRzV2rrtPZthrU5ca+S7rD2DK4PQOKEc6y7zl3XuAoopCgS00l"
    "HUXNrd7V81rtEeXONIXMH6rMPgDjG0kifJZ9bLV6oW4xgVHQrGid0WXA49T+qFP86Cokkq/CroeM08RK74qE6CtH05u2W9tT"
    "Y61f2its8wnowrITTkQ93C2iW3gSoD3BX8VWdtGC8gyx4pIajl3O2HLvrcw8l9WVUrGE6A2W5C5A2eTyQLIeiF/cqFmJEnz2"
    "VtAu0KyxO09Q4fqgwRupHivycK1PhIg==";

// Generated from test_token_expiration_null.json
const char g_signed_test_user_token_expiration_null[] =
    "ewogICAgImlkZW50aXR5IjogInRlc3QiLAogICAgImFjY2VzcyI6IFsiZG93bmxvYWQiLCAidXBsb2FkIl0sCiAgICAidGlt"
    "ZXN0YW1wIjogMTQ1NTUzMDYxNCwKICAgICJleHBpcmVzIjogbnVsbCwKICAgICJhcHBfaWQiOiAiaW8uYmFycS5UZXN0Igp9"
    "Cg==:gf2EBD/k2ZNQYFO07x2dRICigg/sWC//YODgq47tArdEW3wcalUImJQt6r7gnowKfehb63XYn6bM3aNUdQPGy4wqVTa"
    "1Xa1g0Q897+XNK0DIe3Zb4bB/tfcdUbzmaHQDJ6n2Bns19KEdWSuOxz9JjYjTraKMbzXvfDV5xjiufZ57wYJs5Ba743ijnPY"
    "En5RE2vY/B2G8mVMN+6aWUoBetnTOxKNylK5qNKdb1tFEZ7Be5199O9O10FKaFO7p8W0nQtGwkrjbTo8Y4IziGgs+2Lha60f"
    "/n1NSoNa3i8lL5Hi+Z7tHeufFkSpnDDrzcq+TDCGaj3GI5LhK2nbU03SAcQ==";

// Generated from test_token_expiration_specified.json
const char g_signed_test_user_token_expiration_specified[] =
    "ewogICAgImlkZW50aXR5IjogInRlc3QiLAogICAgImFjY2VzcyI6IFsiZG93bmxvYWQiLCAidXBsb2FkIl0sCiAgICAidGlt"
    "ZXN0YW1wIjogMTQ1NTUzMDYxNCwKICAgICJleHBpcmVzIjogICAzMDAwMDAwMDAwLAogICAgImFwcF9pZCI6ICJpby5iYXJx"
    "LlRlc3QiCn0K:oDRBOIEXesepG5/+TNo+AF3Pqi3pmRdd3mWx7hDpUXc5dAU23zRPryt5nj3pPH/zrM7xTR6A1H0yyI0d5gr"
    "OaRs1H3PZ77H4JdW8J+bFTzsVkjxLa1hI1MDDH8LFMoX2lksR8fL8b7VxwVt1hwaVscgdludTz2vuNJdWLPp9Kac5lsHYyAU"
    "Hdm3cXP1GZ3PhBPBBPlv87wahyuw++hFmhBRbsmbAsLtdSlNFlCydZxNYAJDqaRHX48O+VrP5FCN6DTVcsIGNjxzvFOCKQ2A"
    "Jg+9+4dLM9xJClA7Y8rPpIP+LQNIsJFbtT7M8s2I9OzUN4p1WVfgUPp7TgPjgVhw8cQ==";

// Generated from test_token_sync_label_default.json
const char g_signed_test_user_token_sync_label_default[] =
    "ewogICAgImlkZW50aXR5IjogInRlc3QiLAogICAgImFjY2VzcyI6IFsiZG93bmxvYWQiLCAidXBsb2FkIl0sCiAgICAidGlt"
    "ZXN0YW1wIjogMTQ1NTUzMDYxNCwKICAgICJleHBpcmVzIjogbnVsbCwKICAgICJhcHBfaWQiOiAiaW8uYmFycS5UZXN0IiwK"
    "ICAgICJzeW5jX2xhYmVsIjogImRlZmF1bHQiCn0K:vbkNOsFNO00Sy28M/5+rc1bdogu/Ilbg7yzk6cYXB/4bXYB6YNjV8Wi"
    "2YBs1ky86uoyCIKb//Na3uHQU2jPybG37HREos5mfh2rZDE4OU4FXx1El+gcV6KLGEQIaTds2ryhpw9cawbvhGlrN0FGEdl6"
    "GCJZL+mYTg3y5PjysazzgCCHF1n7pROLxzwhCCzTl+cMFktykyhBnTIE5X0+30hO4ovMcruLZfgY2kfJXyeltAPoUVKpxJqJ"
    "+IOb+ROzWppZuZ0RW/s19/2QiTPxj9tfhnU6JoqXxnmuGSYe3pDOZv7utfHBSZcdoHKcklyMOyMCMVxairVFFe8/D+eO7aQ="
    "=";

// Generated from test_token_sync_label_custom.json
const char g_signed_test_user_token_sync_label_custom[] =
    "ewogICAgImlkZW50aXR5IjogInRlc3QiLAogICAgImFjY2VzcyI6IFsiZG93bmxvYWQiLCAidXBsb2FkIl0sCiAgICAidGlt"
    "ZXN0YW1wIjogMTQ1NTUzMDYxNCwKICAgICJleHBpcmVzIjogbnVsbCwKICAgICJhcHBfaWQiOiAiaW8uYmFycS5UZXN0IiwK"
    "ICAgICJzeW5jX2xhYmVsIjogImN1c3RvbSIKfQo=:DiEX4knpjTqyr+DmE/+R3hxNp4oXXCkiyJY+I69NmNJLXLRwsGrn+c3"
    "y1mYv4SQHNxUCI0CJakYslkhYBIc7VhUhTgRMPXCIQumGbWHbYzijEUBX5t/FrvzO9hp7jcg4viEi2HlBBUYK8sBMCBk56Dx"
    "3ueVW9f6BA/h/NGhN8ZRZhqEvSePCHzCIV+Z3R9kAuiB6RbnXglfAIKa993dx9XlJzusA8npnd9mRHPo7fujdsALbPFl2nhm"
    "Ewr95k09EO1qY2gvFlREJYi1RG+9d381RiuEJVA//PpJm0wMCx2GuehOhhKBpEvP3AUjpkf3MR+f5GA2QmVwHfmD1RKBVZQ="
    "=";

const std::string developer_token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE0OTI2MTEzMDN9.cf2s0bUM/da"
                                    "Hq/yp7PG6csktIgObeVeUvmObD8JOUCwC2uA3rMLGjEHPKxxmvZJtSoQq49PkhTpvCSk1ewKR"
                                    "R67U9J/AE1czBQPiit4FgTj/oujXIpNVio9t5oeSd3XqNg66HZhi5F+wsMOJ2hmxL9S+OBjQU"
                                    "yUchEPksKubiFKUPEktdmjewNp2VmdnPNjAdqmIhRyeHSQhl494lOlK/gyae2RUh2wWO1j9K0"
                                    "o24nd0VIr4+61UD/aMDsF70vXEkqPxboB83yu51CpkmqFJ0xklA9f9M1uKUgsOwX07Uf4plRE"
                                    "tYb1QxmoPdnQH3VPvVt4i0Yko/dMgpnuSJj30gQ==";

const std::string enterprise_token = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJBZGFwdGVyIjp0cnVlLCJCYWNrdXAiOnRyd"
                                     "WUsIkxvYWRCYWxhbmNpbmciOnRydWUsIk5vdGlmaWVyIjp0cnVlLCJTeW5jIjp0cnVlLCJpYXQ"
                                     "iOjE1MDc4MzM4MDJ9.SJn2ScgPXXJgRrXzKg-7HlCcwGQ5pQVLPXHiyJhRN54f4dAFsVDjyoqf"
                                     "yV2TO6CibP9UytIaztnnqjFrYq47YsZas9IlkZ6xv3wZRUF4Op_OcCdmuY9kAuGG-fNqBKWaM_"
                                     "woDzrFBigo1os7_FqFU1aC1Jmnh1NZjEPTP5euwWNF92BGcfAdHBkJU86MLvvXLHzGnedkm4Y5"
                                     "Sh5GlHz_UkC7OHflJoXbMUIUi9NMbqH3BbtvCwKHE1Vs-XShNFqbrAJTG6PJxJxIOXfSvgbnxe"
                                     "N3gpm69p-9cfM9O4TjNPoYZy4cPR5UG6NSJ4XDuSg7Wz8kdn9l3IzMiwi-a6Oofw";

const StringData g_partial_sync_result_sets_table_name = "class___ResultSets";


class FakeClock : public sync::Clock {
public:
    template <class R, class P>
    void add_time(std::chrono::duration<R, P> duration) noexcept
    {
        m_now += std::chrono::duration_cast<time_point::duration>(duration).count();
    }

    FakeClock() noexcept
        : m_now(0)
    {
    }

    template <class R, class P>
    FakeClock(std::chrono::duration<R, P> initial_value) noexcept
        : m_now(std::chrono::duration_cast<time_point::duration>(initial_value).count())
    {
    }

    time_point now() const noexcept override
    {
        return time_point{time_point::duration{m_now}};
    }

private:
    std::atomic<time_point::rep> m_now;
};


// HTTPRequestClient is used to send a HTTP request to a server, typically the
// Sync server, and wait for the response. HTTPRequestClient is constructed
// with the server endpoint and request. fetch_response() is a blocking
// function that fetches the HTTP response on the network. get_response()
// is used to retrieve the result afterwards.
class HTTPRequestClient {
public:
    using WriteCompletionHandler = util::UniqueFunction<void(std::error_code, size_t num_bytes_transferred)>;
    using ReadCompletionHandler = util::UniqueFunction<void(std::error_code, size_t num_bytes_transferred)>;

    util::PrefixLogger logger;

    HTTPRequestClient(const std::shared_ptr<util::Logger>& logger_ptr, const network::Endpoint& endpoint,
                      const HTTPRequest& request)
        : logger{"HTTP client: ", logger_ptr}
        , m_endpoint{endpoint}
        , m_http_client{*this, logger_ptr}
        , m_request{request}
    {
    }

    // The network activity happens in fetch_response().
    // fetch_response() is blocking.
    void fetch_response()
    {
        initiate_tcp_connect();
        m_service.run();
    }

    // get_response is used to retrieve the response after
    // fetch_response returns.
    HTTPResponse& get_response()
    {
        return m_response;
    }

    void async_write(const char* data, size_t size, WriteCompletionHandler handler)
    {
        m_socket.async_write(data, size, std::move(handler));
    }

    void async_read_until(char* buffer, size_t size, char delim, ReadCompletionHandler handler)
    {
        m_socket.async_read_until(buffer, size, delim, m_read_ahead_buffer, std::move(handler));
    }

    void async_read(char* buffer, size_t size, ReadCompletionHandler handler)
    {
        m_socket.async_read(buffer, size, m_read_ahead_buffer, std::move(handler));
    }

private:
    network::Service m_service;
    network::Socket m_socket{m_service};
    network::ReadAheadBuffer m_read_ahead_buffer;
    network::Endpoint m_endpoint;
    HTTPClient<HTTPRequestClient> m_http_client;
    HTTPRequest m_request;
    HTTPResponse m_response;

    void initiate_tcp_connect()
    {
        auto handler = [this](std::error_code ec) mutable {
            if (ec != util::error::operation_aborted)
                handle_tcp_connect(ec);
        };
        m_socket.async_connect(m_endpoint, std::move(handler));
        logger.info("Connecting to endpoint '%1:%2'", m_endpoint.address(), m_endpoint.port());
    }

    void handle_tcp_connect(std::error_code ec)
    {
        if (ec) {
            logger.debug("Failed to connect to endpoint '%1:%2': %3", m_endpoint.address(), m_endpoint.port(),
                         ec.message());
            stop();
            return;
        }

        m_socket.set_option(network::SocketBase::no_delay(true));
        logger.debug("Connected to endpoint '%1:%2'", m_endpoint.address(), m_endpoint.port());


        initiate_http_request();
    }

    void initiate_http_request()
    {
        auto handler = [this](HTTPResponse response, std::error_code ec) {
            if (ec != util::error::operation_aborted) {
                if (ec) {
                    logger.debug("HTTP response error, ec = %1", ec.message());
                    stop();
                    return;
                }
                handle_http_response(response);
            }
        };
        m_http_client.async_request(m_request, handler);
    }

    void handle_http_response(const HTTPResponse response)
    {
        logger.debug("HTTP response received, status = %1", int(response.status));
        m_response = response;
        stop();
    }

    void stop()
    {
        m_socket.close();
        m_service.stop();
    }
};


class MultiClientServerFixture {
public:
    enum class ClusterTopology { separate_nodes, two_tiers, one_node_per_tier };

    struct Config {
        Config() {}

        // Optional thread-safe logger. If none is specified, the one available
        // through unit_test::TestContext will be used.
        std::shared_ptr<util::Logger> logger;

        // These values will disable the heartbeats by default.
        milliseconds_type client_ping_period = 100000000;  // do not send pings
        milliseconds_type client_pong_timeout = 100000000; // do not expect pongs
        milliseconds_type server_connection_reaper_timeout = 100000000;
        milliseconds_type server_connection_reaper_interval = 100000000;

        long server_max_open_files = 64;

        bool enable_server_ssl = false;

        std::string server_ssl_certificate_path = get_test_resource_path() + "test_sync_ca.pem";
        std::string server_ssl_certificate_key_path = get_test_resource_path() + "test_sync_key.pem";

        bool disable_upload_compaction = false;

        bool disable_history_compaction = false;
        std::chrono::seconds history_ttl = std::chrono::seconds::max();
        std::chrono::seconds history_compaction_interval = std::chrono::seconds{3600};
        const Clock* history_compaction_clock = nullptr;

        size_t max_download_size = 0x1000000; // 16 MB as in Server::Config
        bool enable_download_bootstrap_cache = false;

#if BARQ_DISABLE_SYNC_MULTIPLEXING
        bool one_connection_per_session = true;
#else
        bool one_connection_per_session = false;
#endif

        bool disable_upload_activation_delay = false;

        ClusterTopology cluster_topology = ClusterTopology::separate_nodes;

        std::string authorization_header_name = "Authorization";

        // Run servers without public key if `server_public_key_path` is the
        // empty string.
        std::string server_public_key_path = test_server_key_path();

        std::optional<std::array<char, 64>> server_encryption_key;

        int server_max_protocol_version = 0;

        bool enable_flx_sync = false;
        std::vector<Server::Config::FLXRule> flx_rules;
        std::shared_ptr<const AccessControl::PublicKeyStore> tenant_public_keys;

        std::set<file_ident_type> server_disable_download_for;

        std::function<Server::SessionBootstrapCallback> server_session_bootstrap_callback;
        std::function<Server::FLXBootstrapBatchCallback> server_flx_bootstrap_batch_callback;

        std::shared_ptr<BindingCallbackThreadObserver> socket_provider_observer;
    };


    MultiClientServerFixture(int num_clients, int num_servers, std::string server_dir,
                             unit_test::TestContext& test_context, Config config = {})
        : m_logger{config.logger ? config.logger : test_context.logger}
        , m_num_servers{num_servers}
        , m_num_clients{num_clients}
        , m_enable_server_ssl{config.enable_server_ssl}
        , m_test_context{test_context}
    {
        BARQ_ASSERT(num_servers >= 1);

        m_server_loggers.resize(num_servers);
        m_client_loggers.resize(num_clients);

        if (num_servers == 1) {
            m_server_loggers[0] = std::make_shared<util::PrefixLogger>("Server: ", m_logger);
        }
        else {
            for (int i = 0; i < num_servers; ++i) {
                std::string prefix = "Server[" + std::to_string(i + 1) + "]: ";
                m_server_loggers[i] = std::make_shared<util::PrefixLogger>(std::move(prefix), m_logger);
            }
        }

        if (num_clients == 1) {
            m_client_loggers[0] = std::make_shared<util::PrefixLogger>("Client: ", m_logger);
        }
        else {
            for (int i = 0; i < num_clients; ++i) {
                std::string prefix = "Client[" + std::to_string(i + 1) + "]: ";
                m_client_loggers[i] = std::make_shared<util::PrefixLogger>(std::move(prefix), m_logger);
            }
        }

        m_servers.resize(num_servers);
        m_server_ports.resize(num_servers);
        std::string listen_address = "localhost";
        std::string listen_port = ""; // Assign automatically
        for (int i = 0; i < num_servers; ++i) {
            std::string dir_name = "server";
            if (num_servers > 1) {
                dir_name += "-" + std::to_string(i + 1);
            }
            std::string dir = util::File::resolve(dir_name, server_dir);
            util::try_make_dir(dir);
            std::optional<PKey> public_key;
            if (!config.server_public_key_path.empty())
                public_key = PKey::load_public(config.server_public_key_path);
            Server::Config config_2;
            config_2.max_open_files = config.server_max_open_files;
            config_2.logger = m_server_loggers[i];
            config_2.token_expiration_clock = &m_fake_token_expiration_clock;
            config_2.ssl = m_enable_server_ssl;
            config_2.ssl_certificate_path = config.server_ssl_certificate_path;
            config_2.ssl_certificate_key_path = config.server_ssl_certificate_key_path;
            config_2.connection_reaper_timeout = config.server_connection_reaper_timeout;
            config_2.connection_reaper_interval = config.server_connection_reaper_interval;
            config_2.max_download_size = config.max_download_size;
            config_2.enable_download_bootstrap_cache = config.enable_download_bootstrap_cache;
            config_2.tcp_no_delay = true;
            config_2.authorization_header_name = config.authorization_header_name;
            config_2.encryption_key = config.server_encryption_key;
            config_2.max_protocol_version = config.server_max_protocol_version;
            config_2.enable_flx_sync = config.enable_flx_sync;
            config_2.flx_rules = config.flx_rules;
            config_2.tenant_public_keys = config.tenant_public_keys;
            config_2.disable_download_for = std::move(config.server_disable_download_for);
            config_2.session_bootstrap_callback = std::move(config.server_session_bootstrap_callback);
            config_2.flx_bootstrap_batch_callback = std::move(config.server_flx_bootstrap_batch_callback);
            m_servers[i] = std::make_unique<Server>(std::move(dir), std::move(public_key), std::move(config_2));
            m_servers[i]->start(listen_address, listen_port);
            m_server_ports[i] = m_servers[i]->listen_endpoint().port();
        }

        m_clients.resize(num_clients);
        for (int i = 0; i < num_clients; ++i) {
            Client::Config config_2;

            m_client_socket_providers.push_back(std::make_shared<websocket::DefaultSocketProvider>(
                m_client_loggers[i], "", config.socket_provider_observer,
                websocket::DefaultSocketProvider::AutoStart{false}));
            config_2.socket_provider = m_client_socket_providers.back();
            config_2.logger = m_client_loggers[i];
            config_2.reconnect_mode = ReconnectMode::testing;
            config_2.ping_keepalive_period = config.client_ping_period;
            config_2.pong_keepalive_timeout = config.client_pong_timeout;
            config_2.one_connection_per_session = config.one_connection_per_session;
            config_2.disable_upload_activation_delay = config.disable_upload_activation_delay;
            config_2.fix_up_object_ids = true;
            m_clients[i] = std::make_unique<Client>(std::move(config_2));
        }

        m_server_threads.resize(num_servers);

        m_simulated_server_error_rates.resize(num_servers);
        m_simulated_client_error_rates.resize(num_clients);

        m_allow_server_errors.resize(num_servers, 0);

        m_connection_state_change_listeners.resize(num_clients);
    }

    MultiClientServerFixture(const MultiClientServerFixture&) = delete;

    ~MultiClientServerFixture()
    {
        unit_test::TestContext& test_context = m_test_context;
        stop();
        for (int i = 0; i < m_num_clients; ++i) {
            m_clients[i]->shutdown_and_wait();
        }
        m_client_socket_providers.clear();
        for (int i = 0; i < m_num_servers; ++i) {
            if (m_server_threads[i].joinable())
                CHECK(!m_server_threads[i].join());
            CHECK_LESS_EQUAL(m_servers[i]->errors_seen(), m_allow_server_errors[i]);
        }
    }

    using ErrorHandler = void(Status status, bool is_fatal);

    // Set an error handler to be used for all sessions of the specified client
    // (\a handler will be copied for each session). Must be called before
    // make_session().
    void set_client_side_error_handler(int client_index, std::function<ErrorHandler> handler)
    {
        auto handler_wrapped = [handler = std::move(handler)](ConnectionState state,
                                                              std::optional<SessionErrorInfo> error_info) {
            if (state != ConnectionState::disconnected)
                return;
            BARQ_ASSERT(error_info);
            handler(error_info->status, error_info->is_fatal);
        };
        m_connection_state_change_listeners[client_index] = std::move(handler_wrapped);
    }

    void set_client_side_error_rate(int client_index, int n, int m)
    {
        BARQ_ASSERT(client_index >= 0 && client_index < m_num_clients);
        auto sim = std::make_pair(n, m);
        // Save the simulated error rate
        m_simulated_client_error_rates[client_index] = sim;

        // Post the new simulated error rate
        using sf = _impl::SimulatedFailure;
        // Post it onto the event loop to update the event loop thread
        m_client_socket_providers[client_index]->post([sim = std::move(sim)](Status) {
            sf::prime_random(sf::sync_client__read_head, sim.first, sim.second,
                             random_int<uint_fast64_t>()); // Seed from global generator
        });
    }

    // Must be called before start().
    void set_server_side_error_rate(int server_index, int n, int m)
    {
        BARQ_ASSERT(server_index >= 0 && server_index < m_num_servers);
        m_simulated_server_error_rates[server_index] = std::make_pair(n, m);
    }

    void start()
    {
        for (int i = 0; i < m_num_servers; ++i)
            m_server_threads[i].start([this, i] {
                run_server(i);
            });

        for (int i = 0; i < m_num_clients; ++i) {
            m_client_socket_providers[i]->start();
        }
    }

    void start_client(int index)
    {
        BARQ_ASSERT(index >= 0 && index < m_num_clients);
        m_client_socket_providers[index]->start();
    }

    // Use either the methods below or `start()`.
    void start_server(int index)
    {
        BARQ_ASSERT(index >= 0 && index < m_num_servers);
        m_server_threads[index].start([this, index] {
            run_server(index);
        });
    }

    void stop_server(int index)
    {
        BARQ_ASSERT(index >= 0 && index < m_num_servers);
        m_servers[index]->stop();
        unit_test::TestContext& test_context = m_test_context;
        if (m_server_threads[index].joinable())
            CHECK(!m_server_threads[index].join());
        CHECK_LESS_EQUAL(m_servers[index]->errors_seen(), m_allow_server_errors[index]);
    }

    void stop_client(int index)
    {
        BARQ_ASSERT(index >= 0 && index < m_num_clients);
        auto& client = get_client(index);
        auto sim = m_simulated_client_error_rates[index];
        if (sim.first != 0) {
            using sf = _impl::SimulatedFailure;
            // If we're using a simulated failure, clear it by posting onto the event loop
            m_client_socket_providers[index]->post([](Status) mutable {
                sf::unprime(sf::sync_client__read_head); // Clear the sim failure set when started
            });
        }
        // We can't wait for clearing the simulated failure since some tests stop the client early
        client.shutdown_and_wait();
    }

    void stop()
    {
        for (int i = 0; i < m_num_clients; ++i)
            m_clients[i]->shutdown();
        for (int i = 0; i < m_num_servers; ++i)
            m_servers[i]->stop();
    }

    Client& get_client(int client_index) noexcept
    {
        return *m_clients[client_index];
    }

    Server& get_server(int server_index) noexcept
    {
        return *m_servers[server_index];
    }

    Session make_session(int client_index, int server_index, DBRef db, std::string barq_identifier,
                         Session::Config config = {})
    {
        //  *ClientServerFixture uses the service identifier "/barq-sync" to distinguish Sync
        //  connections, while the remote service does not.
        config.service_identifier = "/barq-sync";
        config.barq_identifier = std::move(barq_identifier);
        // The fixture server enforces signed access tokens, so an unauthenticated
        // session is rejected at BIND with permission_denied and then hangs on the
        // test's progress/upload waits. Default to the standard signed test token
        // when the caller did not provide one; make_bound_session and the auth
        // tests set an explicit token, so this only affects otherwise-tokenless
        // sessions.
        if (config.signed_user_token.empty())
            config.signed_user_token = g_signed_test_user_token;
        config.server_port = m_server_ports[server_index];
        config.server_address = "localhost";
        if (m_connection_state_change_listeners[client_index]) {
            config.connection_state_change_listener = m_connection_state_change_listeners[client_index];
        }
        else if (!config.connection_state_change_listener) {
            auto fallback_listener = [this](ConnectionState state, std::optional<SessionErrorInfo> error) {
                if (state != ConnectionState::disconnected)
                    return;
                BARQ_ASSERT(error);
                unit_test::TestContext& test_context = m_test_context;
                test_context.logger->error("Client disconnect: %1 (is_fatal=%2)", error->status, error->is_fatal);
                bool client_error_occurred = true;
                CHECK_NOT(client_error_occurred);
                stop();
            };
            config.connection_state_change_listener = fallback_listener;
        }

        return Session{*m_clients[client_index], std::move(db), nullptr, nullptr, std::move(config)};
    }

    Session make_flx_session(int client_index, int server_index, DBRef db,
                             std::shared_ptr<SubscriptionStore> flx_sub_store, std::string barq_identifier,
                             Session::Config config = {})
    {
        config.service_identifier = "/barq-sync";
        config.barq_identifier = std::move(barq_identifier);
        if (config.signed_user_token.empty())
            config.signed_user_token = g_signed_test_user_token;
        config.server_port = m_server_ports[server_index];
        config.server_address = "localhost";
        if (m_connection_state_change_listeners[client_index]) {
            config.connection_state_change_listener = m_connection_state_change_listeners[client_index];
        }
        else if (!config.connection_state_change_listener) {
            auto fallback_listener = [this](ConnectionState state, std::optional<SessionErrorInfo> error) {
                if (state != ConnectionState::disconnected)
                    return;
                BARQ_ASSERT(error);
                unit_test::TestContext& test_context = m_test_context;
                test_context.logger->error("Client disconnect: %1 (is_fatal=%2)", error->status, error->is_fatal);
                bool client_error_occurred = true;
                CHECK_NOT(client_error_occurred);
                stop();
            };
            config.connection_state_change_listener = fallback_listener;
        }

        auto migration_store = MigrationStore::create(db);
        return Session{*m_clients[client_index], std::move(db), std::move(flx_sub_store),
                       std::move(migration_store), std::move(config)};
    }

    Session make_bound_session(int client_index, DBRef db, int server_index, std::string server_path,
                               Session::Config config = {})
    {
        return make_bound_session(client_index, std::move(db), server_index, std::move(server_path),
                                  g_signed_test_user_token, std::move(config));
    }

    Session make_bound_session(int client_index, DBRef db, int server_index, std::string server_path,
                               std::string signed_user_token, Session::Config config = {})
    {
        config.signed_user_token = std::move(signed_user_token);
        return make_session(client_index, server_index, std::move(db), std::move(server_path), std::move(config));
    }

    void cancel_reconnect_delay(int client_index)
    {
        get_client(client_index).cancel_reconnect_delay();
    }

    void allow_server_errors(int server_index, uint_fast64_t max_num_errors)
    {
        m_allow_server_errors[server_index] = uint_least64_t(max_num_errors);
    }

    void set_fake_token_expiration_time(std::int_fast64_t seconds_since_epoch)
    {
        using time_point = sync::Clock::time_point;
        auto duration_1 = std::chrono::seconds(seconds_since_epoch);
        auto duration_2 = std::chrono::duration_cast<time_point::duration>(duration_1);
        auto now_1 = m_fake_token_expiration_clock.now();
        auto now_2 = time_point{duration_2};
        BARQ_ASSERT(now_2 >= now_1);
        m_fake_token_expiration_clock.add_time(now_2 - now_1);
    }

    void set_server_connection_reaper_timeout(milliseconds_type timeout)
    {
        for (int i = 0; i < m_num_servers; ++i)
            m_servers[i]->set_connection_reaper_timeout(timeout);
    }

    void close_server_side_connections()
    {
        for (int i = 0; i < m_num_servers; ++i)
            m_servers[i]->close_connections();
    }

    bool wait_for_session_terminations_or_client_stopped()
    {
        for (int i = 0; i < m_num_clients; ++i) {
            if (!m_clients[i]->wait_for_session_terminations_or_client_stopped())
                return false;
        }
        return true;
    }

    std::string map_virtual_to_real_path(int server_index, const std::string& virt_path)
    {
        std::string real_path;
        if (get_server(server_index).map_virtual_to_real_path(virt_path, real_path)) // Throws
            return real_path;
        throw std::runtime_error("Bad virtual path");
    }

    void inform_server_about_external_change(int server_index, const std::string& virt_path)
    {
        get_server(server_index).recognize_external_change(virt_path); // Throws
    }

private:
    using ConnectionStateChangeListener = Session::ConnectionStateChangeListener;
    using port_type = Session::port_type;
    std::shared_ptr<util::Logger> m_logger;
    const int m_num_servers;
    const int m_num_clients;
    const bool m_enable_server_ssl;
    unit_test::TestContext& m_test_context;
    std::vector<std::shared_ptr<util::Logger>> m_server_loggers;
    std::vector<std::shared_ptr<util::Logger>> m_client_loggers;
    std::vector<std::unique_ptr<Server>> m_servers;
    std::vector<std::unique_ptr<Client>> m_clients;
    std::vector<std::function<ConnectionStateChangeListener>> m_connection_state_change_listeners;
    std::vector<port_type> m_server_ports;
    std::vector<ThreadWrapper> m_server_threads;
    std::vector<std::shared_ptr<websocket::DefaultSocketProvider>> m_client_socket_providers;
    std::vector<std::pair<int, int>> m_simulated_server_error_rates;
    std::vector<std::pair<int, int>> m_simulated_client_error_rates;
    std::vector<uint_least64_t> m_allow_server_errors;
    FakeClock m_fake_token_expiration_clock;

    static std::optional<std::array<char, 64>> make_crypt_key(const std::string& key)
    {
        if (!key.empty()) {
            if (key.size() != 64)
                throw std::runtime_error("Encryption key has wrong size");
            std::array<char, 64> key_2;
            std::copy(key.begin(), key.end(), key_2.data());
            return key_2;
        }
        return {};
    }

    void run_server(int i)
    {
        auto do_run_server = [this, i] {
            auto sim = m_simulated_server_error_rates[i];
            if (sim.first != 0) {
                using sf = _impl::SimulatedFailure;
                sf::RandomPrimeGuard pg(sf::sync_server__read_head, sim.first, sim.second,
                                        random_int<uint_fast64_t>()); // Seed from global generator
                m_servers[i]->run();
            }
            else {
                m_servers[i]->run();
            }
            m_servers[i]->stop();
        };
        unit_test::TestContext& test_context = m_test_context;
        if (CHECK_NOTHROW(do_run_server()))
            return;
        stop();
        m_server_loggers[i]->error("Exception was throw from server[%1]'s event loop", i + 1);
    }
};


class ClientServerFixture : public MultiClientServerFixture {
public:
    using Config = MultiClientServerFixture::Config;

    ClientServerFixture(std::string server_dir, unit_test::TestContext& test_context, Config config = {})
        : MultiClientServerFixture{1, 1, std::move(server_dir), test_context, std::move(config)}
    {
    }

    // Set an error handler to be used for all sessions of the client (\a
    // handler will be copied for each session). Must be called before
    // make_session().
    void set_client_side_error_handler(std::function<ErrorHandler> handler)
    {
        MultiClientServerFixture::set_client_side_error_handler(0, std::move(handler));
    }

    // Must be called before start().
    void set_client_side_error_rate(int n, int m)
    {
        MultiClientServerFixture::set_client_side_error_rate(0, n, m);
    }

    // Must be called before start().
    void set_server_side_error_rate(int n, int m)
    {
        MultiClientServerFixture::set_server_side_error_rate(0, n, m);
    }

    Client& get_client() noexcept
    {
        return MultiClientServerFixture::get_client(0);
    }

    Server& get_server() noexcept
    {
        return MultiClientServerFixture::get_server(0);
    }

    Session make_session(DBRef db, std::string barq_identifier, Session::Config&& config = {})
    {
        return MultiClientServerFixture::make_session(0, 0, std::move(db), std::move(barq_identifier),
                                                      std::move(config));
    }
    Session make_session(std::string const& path, std::string barq_identifier, Session::Config&& config = {})
    {
        auto db = DB::create(make_client_replication(), path);
        return MultiClientServerFixture::make_session(0, 0, std::move(db), std::move(barq_identifier),
                                                      std::move(config));
    }

    Session make_bound_session(DBRef db, std::string server_path = "/test", Session::Config&& config = {})
    {
        return MultiClientServerFixture::make_bound_session(0, std::move(db), 0, std::move(server_path),
                                                            std::move(config));
    }

    Session make_bound_session(DBRef db, std::string server_path, std::string signed_user_token,
                               Session::Config&& config = {})
    {
        return MultiClientServerFixture::make_bound_session(0, std::move(db), 0, std::move(server_path),
                                                            std::move(signed_user_token), std::move(config));
    }

    void cancel_reconnect_delay()
    {
        MultiClientServerFixture::cancel_reconnect_delay(0); // Throws
    }

    void allow_server_errors(uint_fast64_t max_num_errors)
    {
        MultiClientServerFixture::allow_server_errors(0, max_num_errors);
    }

    std::string map_virtual_to_real_path(const std::string& virt_path)
    {
        return MultiClientServerFixture::map_virtual_to_real_path(0, virt_path); // Throws
    }

    void inform_server_about_external_change(const std::string& virt_path)
    {
        MultiClientServerFixture::inform_server_about_external_change(0, virt_path); // Throws
    }
};


class BarqFixture {
public:
    using ErrorHandler = MultiClientServerFixture::ErrorHandler;

    struct Config : Session::Config {
        util::UniqueFunction<ErrorHandler> error_handler;
    };

    BarqFixture(ClientServerFixture&, const std::string& real_path, const std::string& virt_path, Config = {});
    BarqFixture(MultiClientServerFixture&, int client_index, int server_index, const std::string& real_path,
                 const std::string& virt_path, Config = {});
    ~BarqFixture() noexcept;

    void empty_transact();
    void nonempty_transact();

    using TransactFunc = util::FunctionRef<bool(Transaction&)>;

    /// Perform a non-serialized transaction synchronously.
    bool transact(TransactFunc);

    bool wait_for_upload_complete_or_client_stopped();
    bool wait_for_download_complete_or_client_stopped();

    using WaitOperCompletionHandler = Session::WaitOperCompletionHandler;

    void async_wait_for_sync_completion(WaitOperCompletionHandler);
    void async_wait_for_upload_completion(WaitOperCompletionHandler);
    void async_wait_for_download_completion(WaitOperCompletionHandler);

private:
    struct SelfRef {
        util::Mutex mutex;
        BarqFixture* ref = nullptr;
        SelfRef(BarqFixture* r)
            : ref{r}
        {
        }
    };

    const std::shared_ptr<SelfRef> m_self_ref;
    DBRef m_db;
    sync::Session m_session;

    Config setup_error_handler(Config&&);
};


inline BarqFixture::BarqFixture(ClientServerFixture& client_server_fixture, const std::string& real_path,
                                  const std::string& virt_path, Config config)
    : m_self_ref{std::make_shared<SelfRef>(this)}                                                            // Throws
    , m_db{DB::create(make_client_replication(), real_path)}                                                 // Throws
    , m_session{client_server_fixture.make_session(m_db, virt_path, setup_error_handler(std::move(config)))} // Throws
{
}


inline BarqFixture::BarqFixture(MultiClientServerFixture& client_server_fixture, int client_index, int server_index,
                                  const std::string& real_path, const std::string& virt_path, Config config)
    : m_self_ref{std::make_shared<SelfRef>(this)}            // Throws
    , m_db{DB::create(make_client_replication(), real_path)} // Throws
    , m_session{client_server_fixture.make_session(client_index, server_index, m_db, virt_path,
                                                   setup_error_handler(std::move(config)))} // Throws
{
}

inline BarqFixture::~BarqFixture() noexcept
{
    util::LockGuard lock{m_self_ref->mutex};
    m_self_ref->ref = nullptr;
}

inline void BarqFixture::empty_transact()
{
    transact([](Transaction&) {
        return true;
    });
}

inline void BarqFixture::nonempty_transact()
{
    auto func = [](Transaction& tr) {
        TableRef table = tr.get_or_add_table_with_primary_key("class_Table", type_Int, "id");
        int id = 1;
        bool did_create = false;
        while (!did_create)
            table->create_object_with_primary_key(id++, &did_create);
        return true;
    };
    transact(func);
}

inline bool BarqFixture::transact(TransactFunc transact_func)
{
    auto tr = m_db->start_write(); // Throws
    if (!transact_func(*tr))       // Throws
        return false;
    version_type new_version = tr->commit();        // Throws
    m_session.nonsync_transact_notify(new_version); // Throws
    return true;
}

inline bool BarqFixture::wait_for_upload_complete_or_client_stopped()
{
    return m_session.wait_for_upload_complete_or_client_stopped();
}

inline bool BarqFixture::wait_for_download_complete_or_client_stopped()
{
    return m_session.wait_for_download_complete_or_client_stopped();
}

inline void BarqFixture::async_wait_for_sync_completion(WaitOperCompletionHandler handler)
{
    m_session.async_wait_for_sync_completion(std::move(handler));
}

inline void BarqFixture::async_wait_for_upload_completion(WaitOperCompletionHandler handler)
{
    m_session.async_wait_for_upload_completion(std::move(handler));
}

inline void BarqFixture::async_wait_for_download_completion(WaitOperCompletionHandler handler)
{
    m_session.async_wait_for_download_completion(std::move(handler));
}

inline BarqFixture::Config BarqFixture::setup_error_handler(Config&& config)
{
    if (config.error_handler) {
        config.connection_state_change_listener =
            [handler = std::move(config.error_handler)](ConnectionState state,
                                                        const std::optional<SessionErrorInfo>& error_info) {
                if (state != ConnectionState::disconnected)
                    return;
                BARQ_ASSERT(error_info);
                handler(error_info->status, error_info->is_fatal);
            };
    }
    return std::move(config);
}
} // namespace barq::fixtures
